#######################################################################
# Makefile generated by './configure' at Sun Jun 25 20:51:58 CDT 2017
# Using flags:
#	-DCMAKE_VERBOSE_MAKEFILE=1
#	-DDOMLIB_PATH=domlib
#######################################################################

all clean install:
	make -C build/Linux-x86_64 $@ $(MAKEFLAGS)

distclean:
	rm -rvf build/Linux-x86_64 Makefile

